// i18n/langs.js (SEM <script>)
window.I18N_DICT = {
  pt:{ brand:"De Papo com a PRY", menu_inicio:"Início", menu_mentoria:"Mentoria",
    menu_apostila:"Apostila", menu_prova:"Prova", menu_gabarito:"Gabarito",
    menu_sentidos:"5 Sentidos", menu_curso:"Curso", menu_prof:"Professor",
    menu_loja:"Loja & Música",
    hero_apostila_titulo:"Apostila: Governo do Espírito",
    hero_apostila_sub:"Mentoria Terapêutica Pastoral com a Pastora Priscila Fagundes — De Papo com a PRY",
    sec_sobre_estudo:"Sobre este estudo",
    sec_sobre_estudo_desc:"Conteúdo base da Formação em Terapia Cristã — módulo Governo do Espírito.",
    aula1_titulo:"Aula 1 — O Governo do Espírito e a mente", aula1_desc:"Audição, mente renovada e obediência.",
    aula2_titulo:"Aula 2 — Disciplina da alma e afetos ordenados", aula2_desc:"Ritmos espirituais, intercessão e caráter.",
    aula3_titulo:"Aula 3 — Alinhamento espiritual e prática", aula3_desc:"Discernimento para decisões e serviço.",
    aula4_titulo:"Aula 4 — Trabalho final e debate", aula4_desc:"Síntese bíblica aplicada e entrega do texto.",
    aula_extra_titulo:"Aula Extra — Ezer: A mulher em aliança", aula_extra_desc:"Identidade e vocação feminina sob o Governo do Espírito.",
    btn_ouvir_spotify:"Ouvir no Spotify", btn_baixar_pdf:"Baixar PDF",
    btn_baixar_apostila:"Baixar PDF desta apostila", btn_cadastrar:"Quero me cadastrar",
    btn_ler_apostila:"Ler Apostila", btn_ir_prova:"Ir para a Prova",
    rodape_copyright:"© 2025 Todos os direitos reservados · Pastora Priscila Fagundes",
    rodape_frase:"Cuidar da alma é restaurar o Governo do Espírito.",
    rodape_site_oficial:"Site oficial da Mentoria Pastora Priscila Fagundes",
    redes_instagram:"Instagram", redes_whatsapp:"WhatsApp", redes_youtube:"YouTube"
  },
  en:{ brand:"De Papo with PRY", menu_inicio:"Home", menu_mentoria:"Mentoring",
    menu_apostila:"Workbook", menu_prova:"Exam", menu_gabarito:"Answer Key",
    menu_sentidos:"5 Senses", menu_curso:"Course", menu_prof:"Teacher", menu_loja:"Store & Music",
    hero_apostila_titulo:"Workbook: Government of the Spirit",
    hero_apostila_sub:"Therapeutic Mentoring with Pastor Priscila Fagundes — De Papo with PRY",
    sec_sobre_estudo:"About this study",
    sec_sobre_estudo_desc:"Foundational content of the Christian Therapy Training — Government of the Spirit module.",
    aula1_titulo:"Class 1 — The Spirit’s Government and the Mind", aula1_desc:"Hearing, renewed mind and obedience.",
    aula2_titulo:"Class 2 — Ordering the Soul", aula2_desc:"Spiritual rhythms, intercession and character.",
    aula3_titulo:"Class 3 — Spiritual Alignment and Practice", aula3_desc:"Discernment for decisions and service.",
    aula4_titulo:"Class 4 — Final Paper and Debate", aula4_desc:"Applied biblical synthesis and paper.",
    aula_extra_titulo:"Extra Class — Ezer: Woman in Covenant", aula_extra_desc:"Identity and vocation under the Spirit’s Government.",
    btn_ouvir_spotify:"Listen on Spotify", btn_baixar_pdf:"Download PDF",
    btn_baixar_apostila:"Download this workbook (PDF)", btn_cadastrar:"Sign up",
    btn_ler_apostila:"Open Workbook", btn_ir_prova:"Go to Exam",
    rodape_copyright:"© 2025 All rights reserved · Pastor Priscila Fagundes",
    rodape_frase:"Caring for the soul restores the Government of the Spirit.",
    rodape_site_oficial:"Official site of the Mentoring by Pastor Priscila Fagundes",
    redes_instagram:"Instagram", redes_whatsapp:"WhatsApp", redes_youtube:"YouTube"
  },
  es:{ /* ...igual ao que já te passei... */ },
  it:{ /* ... */ }, fr:{/* ... */}, de:{/* ... */}, ar:{/* ... */}, he:{/* ... */}
};
